// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmVXGEZcDHHbxrXpnHPbFwKp0Xgb9DBfo',
    appId: '1:954543990570:web:c2b58c4b90261663eda053',
    messagingSenderId: '954543990570',
    projectId: 'gatekee-4225f',
    authDomain: 'gatekee-4225f.firebaseapp.com',
    storageBucket: 'gatekee-4225f.firebasestorage.app',
    measurementId: 'G-LQ6TP7YRMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKgCW2xE-II4D4vesLlYULVon-ZV1k-c8',
    appId: '1:954543990570:android:2fdda7504195e6bdeda053',
    messagingSenderId: '954543990570',
    projectId: 'gatekee-4225f',
    storageBucket: 'gatekee-4225f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdBfil2QVj1fcVxaohswPI3Q-N8jZGLfg',
    appId: '1:954543990570:ios:fe1b9648cac17a50eda053',
    messagingSenderId: '954543990570',
    projectId: 'gatekee-4225f',
    storageBucket: 'gatekee-4225f.firebasestorage.app',
    iosBundleId: 'com.example.s51Chainsaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdBfil2QVj1fcVxaohswPI3Q-N8jZGLfg',
    appId: '1:954543990570:ios:fe1b9648cac17a50eda053',
    messagingSenderId: '954543990570',
    projectId: 'gatekee-4225f',
    storageBucket: 'gatekee-4225f.firebasestorage.app',
    iosBundleId: 'com.example.s51Chainsaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmVXGEZcDHHbxrXpnHPbFwKp0Xgb9DBfo',
    appId: '1:954543990570:web:332b1295e7572c92eda053',
    messagingSenderId: '954543990570',
    projectId: 'gatekee-4225f',
    authDomain: 'gatekee-4225f.firebaseapp.com',
    storageBucket: 'gatekee-4225f.firebasestorage.app',
    measurementId: 'G-8Q398DZQBE',
  );
}